"""init

Revision ID: b75797d4e645
Revises: 
Create Date: 2026-04-26 03:46:56.677063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b75797d4e645'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=50), nullable=True),
    sa.Column('away_team', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('game_pk')
    )
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('at_bat_index', sa.Integer(), nullable=False),
    sa.Column('pitch_number', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=True),
    sa.Column('inning_half', sa.String(length=6), nullable=True),
    sa.Column('pitcher_id', sa.Integer(), nullable=True),
    sa.Column('batter_id', sa.Integer(), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('outs', sa.Integer(), nullable=True),
    sa.Column('on_1b', sa.Boolean(), nullable=True),
    sa.Column('on_2b', sa.Boolean(), nullable=True),
    sa.Column('on_3b', sa.Boolean(), nullable=True),
    sa.Column('pitch_type', sa.String(length=30), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('start_speed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitches')
    op.drop_table('games')
    # ### end Alembic commands ###
